//
//  hu.swift
//  Flowers
//
//  Created by Jozsef Romhanyi on 20.09.15.
//  Copyright © 2015 Jozsef Romhanyi. All rights reserved.
//


let huDictionary: [TextConstants: String] = [
    .tcAktLanguage:      "hu",
    .tcLevel:            "Szint%",
    .tcLevelScore:       "Pontszám%",
    .tcScoreHead:        "Pontszám",
    .tcCardHead:         "Kártyák",
    .tcScore:            "Pontszám",
    .tcTime:             "Idő",
    .tcActScore:         "Az utolsó játék pontszáma: ",
    .tcTargetScore:      "Elérendö pontszám: ",
    .tcGameLost:         "Vesztettél!",
    .tcGameLost3:        "3-szor vesztettél. Előző szintre vissza!!!",
    .tcTargetNotReached: "A cél nem teljesült",
    .tcSpriteCount:      "Virágok száma:",
    .tcCardCount:        "Kártyalapok száma:",
    .tcReturn:           "Vissza",
    .tcok:               "OK",
    .tcGameComplete:     "Játék % befejezve!",
    .tcNoMessage:        "nem létező üzenet",
    .tcTimeout:          "Lejárt az időd",
    .tcGameOver:         "Vesztettél",
    .tcCongratulations:  "Gratulálok ",
    .tcChooseName:       "Játékosok listája",
    .tcVolume:           "Hangerő",
    .tcCountHelpLines:   "Segédvonalak száma",
    .tcLanguage:         "Nyelv",
    .tcEnglish:          "English (Angol)",
    .tcGerman:           "Deutsch (Német)",
    .tcHungarian:        "Magyar (Magyar)",
    .tcRussian:          "Русский (Orosz)",
    .tcCancel:           "Mégsem",
    .tcDone:             "Kész",
    .tcModify:           "Módosítás",
    .tcDelete:           "Eltávolítás",
    .tcNewName:          "Új játékos",
    .tcChooseLanguage:   "Nyelv kiválasztás",
    .tcPlayer:           "Játékos: %",
    .tcGameModus:        "Játékmód",
    .tcSoundVolume:      "Háttérzajok hangerő",
    .tcMusicVolume:      "Zene hangerő",
    .tcStandardGame:     "Játék virágokkal",
    .tcCardGame:         "Kártyajáték",
    .tcPreviousLevel:    "Előző szint",
    .tcNextLevel:        "Következő szint",
    .tcNewGame:          "Új játék",
    .tcGameAgain:        "Újra játszom",
    .tcChooseGame:       "Válassz:",
    .tcCompetitionHeader:"Verseny % partnerrel",
    .tcTippCount:        "Lehetséges lépések száma: ",
    .tcStatistics:       "%. játék %. szint",
    .tcActTime:          "A játék időtartama: ",
    .tcBestTimeForLevel: "A szint legjobb ideje: ",
    .tcBestTime:         "Legjobb idő",
    .tcAllTimeForLevel:  "A szint teljes játékideje: ",
    .tcAllTime:          "Idő",
    .tcCountPlaysForLevel: "Eddig % játékot játszottál",
    .tcCountPlays:        "Játékok",
    .tcCountCompetitions: "Verseny",
    .tcCountVictorys:     "Győzelem / Vereség",
    .tcBestScore:        "Legjobb pontszám",
    .tcGameCompleteWithBestScore: "Új pontszám rekord a(z) % szinten!",
    .tcGameCompleteWithBestTime:  "Legjobb idő a(z) % szinten",
    .tcGuest:            "Vendég",
    .tcAnonym:           "Anonymus",
    .tcStatistic:        "Statisztikák",
    .tcPlayerStatisticHeader: "% statisztikái %",
    .tcPlayerStatisticLevel: "% statisztikái, szint: % (%), csomagok: %",
    .tcStatisticOfGame:  "%. játék statistikája",
    .tcBestScoreOfGame:   "Legjobb pontszám % %",
    .tcYourScore:         "Pontszámod %",
    .tcReachedScore:      "Elért pontszám: %",
    .tcTimeBonus:          "Idő bonus: %",
    .tcYouAreTheBest:    "Tiéd a legjobb pontszám: %",
    .tcGameNumber:       "Játék: #%",
//    .tcChooseGameNumber: "Válassz játékot",
//    .TCPlayerStatistic:  "Játékos statisztika",
//    .TCGameStatistic:    "Játék statisztika",
    .tcCompetition:      "Verseny",
    .tcCompetitionShort: "Verseny",
    .tcGame:             "Játék",
    .tcChoosePartner:    "Válassz ellenfelet:",
    .tcWantToPlayWithYou:"% szeretne veled játszani!",
    .tcOpponent:          "Ellenfél: %",
    .tcOpponentHasFinished: "% befejezte a #% játékot!\r\n" +
                            "pontszáma: %\r\n" +
                            "bonuszpontjai: %\r\n" +
                            "totál pontszáma: %\r\n" +
                            "a te pontszámod: %\r\n ",
    .tcHeWon:               "% győzött % - %\r\n" +
                            "Sajnálom :-(",
    .tcYouWon:              "Te győztél % - %!\r\n" +
                            "Gratulálok ;-) !!!",
    .tcYouHaveFinished: "Befejezted a #% játékot!\r\n" +
                        "Pontjaid: %\r\n" +
                        "Bónuszpontjaid: %\r\n" +
                        "Totál Pontszámod: %\r\n" +
                        "% pontjai: %\r\n ",
    .tcOpponentNotPlay: "% nem akar veled játszani!",
    .tcPeerToPeerVersionIsHigher: "% Kommunikációs Verziója magasabb, töltsd le a játék legújabb verzióját, hogy vele versenyezhess!",
    .tcPeerToPeerVersionIsLower: "% Kommunikációs Verziója kisebb, le kell töltenie a játék legújabb verzióját, hogy veled versenyezhessen!",
    .tcGameArt:         "Tipus",
    .tcVictory:         "Győzelem",
    .tcStart:           "Start",
    .tcSettings:        "Beállítások",
    .tcHelp:            "Segitség",
    .tcTipps:           "Tippek",
    .tcUndo:            "Vissza",
    .tcStopCompetition: "Verseny leállítása",
    .tcOpponentStoppedTheGame: "% leállította a játékot",
    .tcAreYouSureToDelete: "Biztosan törölni akarod %-t?\r\n" +
                        "Minden adata törölve lesz!",
    .tcHelpURL:         "http://jogaxplay.hu/portl/hu",
    .tcj:               "J",
    .tcd:               "Q",
    .tck:               "K",
    .tcWhoIs:           "Kicsoda",
    .tcName:            "Név",
    .tcPlayerType:      "Én",
    .tcOpponentType:    "Ellenfél",
    .tcBestPlayerType:  "Legjobb játékos",
    .tcChooseLevel:     "Válassz szintet és opciókat",
    .tcLevelAndGames:   "Szint (lejátszva)",
    .tcSize:            "Formátum:",
    .tcPackage:         "Csomag: %",
    .tcHelpLines:       "Segédvonalak:",
    .tcAutoPlayNormal:  "Automatikus lejátszás",
    .tcAutoPlayNewTest: "Automatikus teszt játékok",
    .tcAutoPlayErrors:  "Hibás játékok ismétlése",
    .tcAutoPlayTable:  "Automatikus játék teszt táblázatból",
    .tcReplay:          "Visszajátszás",
    .tcActivateAutoPlay: "Automatikus lejátszás aktiválása",
    .tcLevelAndPackage: "Csomag:%, Szint:%, Formátum:%",
    .tcAllGamesCount:   "Games: % / %, %",
    .tcPkgTxt:          "%. P: % / %",
    .tcNoMoreSteps:     "Hoppá! Ez a lépés lehetetlenné tenné a játék befejezését --> ezért vissza",
    .tcThereIsNoPartner: "Nincsenek játékosok a közelben!",
    .tcIsPlayingWith:   " ellenfele %",
    .tcWriteReview:     "Írj véleményt az App Store-ban",
    .tcConnectGC:       "Kapcsolódás a Game Center-hez",
    .tcDisconnectGC:    "Lekapcsolódás a Game Center-ről",
    .tcShowGameCenter:  "Mutasd a Game Center-t",
    .tcMyPlace:          "%. Hely (én): %",
    .tcBestPlace:        "1. Hely (%): %",
    .tcAskForGameCenter: "Most már csatlakozhat a Game Centerhez, \r\n" +
                         "hogy megnézze, hány pontja van a többi játékosnak.",
    .tcAskLater:        "Kérdezz később",
    .tcAskNoMore:       "Ne kérdezz többé",
    .tcOnlineGame:      "Online Játék",
    .tcMatchDisconnected: "% kiszállt a versenyből",
    .tcIChooseTheParams: "%: Csomag:%, Szint:%\r\n" +
                              "Én: Csomag:%, Szint:%\r\n" +
                            "Elfogadom a Paramétereit?",
    .tcPartnerChooseTheParams: "%: Csomag:%, Szint:%\r\n" +
                                "Én: Csomag:%, Szint:%\r\n" +
                                "Várakozás % döntésére!",
    .tcPartnerParametersAre: "% és Én (%)\r\n" +
                                "azonos szinten:\r\n" +
                                "Csomag:%, Szint:%",
    .tcNoWait:                  "Nem várok tovább!",
    .tcYes:                     "Igen",
    .tcNo:                      "Nem",
    .tcFriend:                  "Barát: ",
    .tcWaitForOpponent:           "Ellenfél keresése\r\n" +
                                "Kérlek várj!",
    .tcAllPlayers:          "Automatikus játékosválasztás",
]
